#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/code
export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python3.4
export SUBLIME=subl
export EDITOR="$SUBLIME --wait"
export PATH=/usr/local/git/bin:$PATH
export PATH=$PATH:/Library/PostgreSQL/9.3/bin/

source /usr/local/bin/virtualenvwrapper.sh